# Basic Data Operation 
`update date: 07/08/2021`

`Author: thirteen-bears`

`Based on d2l`

## Build Arrays

In [11]:
import torch # "ctrl+enter" to run the cell

In [59]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
x.shape

torch.Size([12])

In [14]:
x.numel() #number of element

12

In [15]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [26]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [25]:
torch.tensor([[1,2,3],[2,3,4],[3,4,1],[4,1,2]])
torch.tensor([[1,2,3],[2,3,4],[3,4,1],[4,1,2]]).shape

torch.Size([4, 3])

In [24]:
torch.tensor([[[1,2,3],[2,3,4],[3,4,1],[4,1,2]]])
torch.tensor([[[1,2,3],[2,3,4],[3,4,1],[4,1,2]]]).shape

torch.Size([1, 4, 3])

## Basic data operation

In [28]:
x = torch.tensor([1.0,2,4,8]) #1.0 to generate float
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [33]:
X = torch.arange(12,dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[1.0,2,3,4],[2,3,4,1],[3,4,1,2]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[1., 2., 3., 4.],
         [2., 3., 4., 1.],
         [3., 4., 1., 2.]]))

In [35]:
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)
# dim = 0 : keep row the same, add to column (stack up)
# dim = 1 : keep col the same, add to row

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 2.,  3.,  4.,  1.],
         [ 3.,  4.,  1.,  2.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  1.],
         [ 8.,  9., 10., 11.,  3.,  4.,  1.,  2.]]))

In [36]:
X==Y # using logic to build a  tensor

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [37]:
X.sum() # to one dim dimension

tensor(66.)

## Note:Broadcasting Mechanism

In [39]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

- Pre-condition: same dimension: both are two dimension
- The column of a = the row of b
- a->(3,2) duplicate
- b->(3,2) duplicate

In [40]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## Change the value of array

In [46]:
X = torch.arange(12,dtype = torch.float32).reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [43]:
X[-1],X[1:3] # final row, two rows

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [44]:
X[1,2] = 9 # change the value in X
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [45]:
X[1:3,2] = 100 #change the values in a region
X

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 100.,   7.],
        [  8.,   9., 100.,  11.]])

## Reallocate RAM

In [49]:
before = id(Y)
Y =Y+X
id(Y) == before  # the output means that the RAM of Y has been changed

False

How do we keep the RAM of Y as the same?

Method1:

In [52]:
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))

Z[:] = X+Y
print('id(Z):',id(Z)) # do not change the RAM of Z
Z = X+Y
print('id(Z):',id(Z)) # change the RAM of Z

id(Z): 140402537923712
id(Z): 140402537923712
id(Z): 140402537926144


Method2:

In [53]:
before = id(X)
X+=Y  # here can save RAM
id(X)== before

True

## Convert to Numpy

Tensor <-> Numpy

In [61]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B) # use "type" to get type 

(numpy.ndarray, torch.Tensor)

Special case: the size of tensor == 1

In [56]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## Q&A

In [58]:
a = torch.arange(12)
b = a.reshape((3,4))
b[:] = 2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])