## Basic Linear Algerithm

In [1]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([3.0])
x**y

tensor([27.])

In [2]:
len(x),x.shape

(1, torch.Size([1]))

In [8]:
A =torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

## Transpose

In [5]:
A.T # transpose of matrix A

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
X = torch.arange(24).reshape(2,3,4) # 2:h,3:row,4:column
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## Reallocate RAM

In [55]:
A =torch.arange(20,dtype = torch.float32).reshape(5,4)
C = A # C,A use the same id
C+=A
C,A,id(C),id(A)

(tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 140694011026176,
 140694011026176)

In [56]:
B = A.clone() # reallocate the RAM of A, then B and A will not have any other connection
B+=A
B,A,id(B),id(A)

(tensor([[ 0.,  4.,  8., 12.],
         [16., 20., 24., 28.],
         [32., 36., 40., 44.],
         [48., 52., 56., 60.],
         [64., 68., 72., 76.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 140694011050240,
 140694011026176)

## Multiplication, Sum, Norm

In [57]:
A*B #multiply by element

tensor([[   0.,    8.,   32.,   72.],
        [ 128.,  200.,  288.,  392.],
        [ 512.,  648.,  800.,  968.],
        [1152., 1352., 1568., 1800.],
        [2048., 2312., 2592., 2888.]])

In [58]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a+X,a*X

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

In [37]:
x=torch.arange(4.0).reshape(2,2,1)
# sum is always a scalar regardless of the shape of x
# how to calculate mean of X
x,x.sum(),x.sum()/x.numel(),x.mean() 

(tensor([[[0.],
          [1.]],
 
         [[2.],
          [3.]]]),
 tensor(6.),
 tensor(1.5000),
 tensor(1.5000))

In [60]:
X = torch.arange(40).reshape(2,5,4)
# dim = 1: add "5" elements together
# "keepdims=True" we keep the dim as 1, then we can use broadcast mechanism (2,1,4)
# "keepdims=False" we remove the dim (2,4)
sum_X = X.sum(dim=1,keepdims=True)
sum_X1 = X.sum(dim=1)
X.shape,sum_X.shape,sum_X1.shape

(torch.Size([2, 5, 4]), torch.Size([2, 1, 4]), torch.Size([2, 4]))

In [42]:
X/sum_X #broadcast mechanism

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [43]:
X.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])

In [45]:
# dot multipulation
x = torch.ones(4,dtype = torch.float32)
y = torch.arange(4,dtype = torch.float32)
torch.dot(x,y),(x*y).sum()

(tensor(6.), tensor(6.))

In [49]:
A.shape,x.shape,torch.mv(A,x) #multiply with vector

(torch.Size([5, 4]), torch.Size([4]), tensor([ 12.,  44.,  76., 108., 140.]))

In [50]:
B = torch.ones(4,3)
torch.mm(A,B) # matrix multiplication

tensor([[ 12.,  12.,  12.],
        [ 44.,  44.,  44.],
        [ 76.,  76.,  76.],
        [108., 108., 108.],
        [140., 140., 140.]])

In [51]:
U = torch.tensor([4.0,3,0])
torch.norm(U) # L2-norm

tensor(5.)

In [53]:
torch.norm(torch.ones(4,9)) # square+sqrt

tensor(6.)